
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, ttk, Scale


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()
window.title("Azoth Lake - v1.6")
window.geometry("800x400")
window.configure(bg = "#1E1D22")

# ----- Change the ttk style so that ComboBoxes can be modified ----- #
style = ttk.Style()
style.theme_use('alt')

# ----- Window Icon ----- #
p1 = PhotoImage(file=relative_to_assets("favicon.png"))
window.iconphoto(False, p1)

# ----- Canvas Settings ----- #
canvas = Canvas(
    window,
    bg = "#1E1D22",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# ----- Canvas Background ----- #
canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("fishingbot/image_1.png"))
image_1 = canvas.create_image(
    400.0,
    200.0,
    image=image_image_1
)

# ----- Version + Detection Headings - Text ----- #
canvas.create_text(
    5.0,
    370.0,
    anchor="nw",
    text="Client Version - \nDetection Status -",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Version Status - Text ----- #
canvas.create_text(
    90.0,
    370.0,
    anchor="nw",
    text="Updated",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Detection Status - Text ----- #
canvas.create_text(
    105.0,
    385.0,
    anchor="nw",
    text="Undetected",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Details - Text ----- #
canvas.create_text(
    715.0,
    370.0,
    anchor="ne",
    text="Discord User - \nDiscord Server - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Program Creator Discord - Text ----- #
canvas.create_text(
    795.0,
    370.0,
    anchor="ne",
    text="AzothLake#0261",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Server Link - Text ----- #
canvas.create_text(
    795.0,
    385.0,
    anchor="ne",
    text="vwWJCFkK6a",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Time Remaining Heading - Text ----- #
canvas.create_text(
    323.0,
    380.0,
    anchor="nw",
    text="Time Remaining - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Time Remaining - Text ----- #
canvas.create_text(
    426.0,
    380.0,
    anchor="nw",
    text="365 Days",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("fishingbot/image_2.png"))
image_2 = canvas.create_image(
    708.0,
    228.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("fishingbot/image_3.png"))
image_3 = canvas.create_image(
    709.0,
    72.0,
    image=image_image_3
)

# ----- Bot Selection/Back Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    selection_button_image = PhotoImage(file=relative_to_assets("fishingbot/selection_button-active.png"))
    selection_button.config(image=selection_button_image)
    selection_button.image = selection_button_image

def on_leave(e):
    selection_button_image = PhotoImage(file=relative_to_assets("fishingbot/selection_button.png"))
    selection_button.config(image=selection_button_image)
    selection_button.image = selection_button_image

# -- Create the button
selection_button_image = PhotoImage(
    file=relative_to_assets("fishingbot/selection_button.png"))
selection_button = Button(
    image=selection_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Bot Selection clicked"),
    relief="flat"
)

# -- Place the button
selection_button.place(
    x=408.0,
    y=295.0,
    width=135.0,
    height=32.0
)

# -- Bind the enter + leave events
selection_button.bind("<Enter>", on_enter)
selection_button.bind("<Leave>", on_leave)

# ----- Start Bot Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    start_button_image = PhotoImage(file=relative_to_assets("fishingbot/start_button-active.png"))
    start_button.config(image=start_button_image)
    start_button.image = start_button_image

def on_leave(e):
    start_button_image = PhotoImage(file=relative_to_assets("fishingbot/start_button.png"))
    start_button.config(image=start_button_image)
    start_button.image = start_button_image

# -- Create the button
start_button_image = PhotoImage(
    file=relative_to_assets("fishingbot/start_button.png"))
start_button = Button(
    image=start_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Start Button clicked"),
    relief="flat"
)

# -- Place the button
start_button.place(
    x=332.0,
    y=336.0,
    width=135.0,
    height=32.0
)

# -- Bind the enter + leave events
start_button.bind("<Enter>", on_enter)
start_button.bind("<Leave>", on_leave)

# ----- Update Bot Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    update_button_image = PhotoImage(file=relative_to_assets("fishingbot/update_button-active.png"))
    update_button.config(image=update_button_image)
    update_button.image = update_button_image

def on_leave(e):
    update_button_image = PhotoImage(file=relative_to_assets("fishingbot/update_button.png"))
    update_button.config(image=update_button_image)
    update_button.image = update_button_image

# -- Create the button
update_button_image = PhotoImage(
    file=relative_to_assets("fishingbot/update_button.png"))
update_button = Button(
    image=update_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Update Button clicked"),
    relief="flat"
)

# -- Place the button
update_button.place(
    x=256.0,
    y=295.0,
    width=135.0,
    height=32.0
)

# -- Bind the enter + leave events
update_button.bind("<Enter>", on_enter)
update_button.bind("<Leave>", on_leave)

entry_image_0 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_1.png"))
entry_bg_0 = canvas.create_image(
    467.0,
    263.5,
    image=entry_image_0
)
entry_0 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_0.place(
    x=420.0,
    y=251.0,
    width=94.0,
    height=23.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_1.png"))
entry_bg_1 = canvas.create_image(
    333.0,
    263.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_1.place(
    x=286.0,
    y=251.0,
    width=94.0,
    height=23.0
)

logout_heading_image = PhotoImage(
    file=relative_to_assets("fishingbot/logout_heading.png"))
logout_heading = canvas.create_image(
    467.0,
    224.0,
    image=logout_heading_image
)

image_image_4 = PhotoImage(
    file=relative_to_assets("fishingbot/image_4.png"))
image_4 = canvas.create_image(
    332.0,
    224.0,
    image=image_image_4
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_2.png"))
entry_bg_2 = canvas.create_image(
    534.0,
    185.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_2.place(
    x=487.0,
    y=173.0,
    width=94.0,
    height=23.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("fishingbot/image_5.png"))
image_5 = canvas.create_image(
    534.0,
    146.0,
    image=image_image_5
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_3.png"))
entry_bg_3 = canvas.create_image(
    400.0,
    185.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_3.place(
    x=353.0,
    y=173.0,
    width=94.0,
    height=23.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("fishingbot/image_6.png"))
image_6 = canvas.create_image(
    399.0,
    146.0,
    image=image_image_6
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_4.png"))
entry_bg_4 = canvas.create_image(
    266.0,
    185.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_4.place(
    x=219.0,
    y=173.0,
    width=94.0,
    height=23.0
)

image_image_7 = PhotoImage(
    file=relative_to_assets("fishingbot/image_7.png"))
image_7 = canvas.create_image(
    265.0,
    146.0,
    image=image_image_7
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_5.png"))
entry_bg_5 = canvas.create_image(
    534.0,
    107.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_5.place(
    x=487.0,
    y=95.0,
    width=94.0,
    height=23.0
)

image_image_8 = PhotoImage(
    file=relative_to_assets("fishingbot/image_8.png"))
image_8 = canvas.create_image(
    534.0,
    72.0,
    image=image_image_8
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_6.png"))
entry_bg_6 = canvas.create_image(
    400.0,
    107.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_6.place(
    x=353.0,
    y=95.0,
    width=94.0,
    height=23.0
)

image_image_9 = PhotoImage(
    file=relative_to_assets("fishingbot/image_9.png"))
image_9 = canvas.create_image(
    400.0,
    72.0,
    image=image_image_9
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("fishingbot/entry_7.png"))
entry_bg_7 = canvas.create_image(
    265.0,
    107.5,
    image=entry_image_7
)

# ----- Bait Input - ComboBox ----- #
# -- Define the custom styling for the bait combobox
style.map('custom.TCombobox', fieldbackground=[('readonly','#28272E')], foreground=[('readonly','#D5D5D5')], 
selectbackground=[('readonly','#28272E')], background=[('readonly','#28272E')], arrowcolor=[('readonly','#28272E')], 
arrowsize=[('readonly','-1')])

# -- List items for the bait combobox
baits = ["No Bait", "Oytser Bait", "Clam Bait", "Meat Bait", "Firefly Bait", "Woodlouse Bait", "Bread Bait", 
"Electric Eel Bait", "Snail Bait", "Fish Bait", "Glowworm Bait", "Nightcrawler Bait", "Cheese bait"]
bait_list_combo = ttk.Combobox(window, values=baits, state="readonly", font="Montserrat 10", style='custom.TCombobox', cursor="hand2")
bait_list_combo.set("Choose a bait")
bait_list_combo.place(x=209, y=96, width=110)


image_image_10 = PhotoImage(
    file=relative_to_assets("fishingbot/image_10.png"))
image_10 = canvas.create_image(
    265.0,
    72.0,
    image=image_image_10
)

# ----- Casting Power Input - Scale ----- #
cast_power_input=Scale(window, from_=10, to=0, sliderrelief='flat', highlightthickness=0, 
background='#28272E', fg='#D5D5D5', troughcolor='#68676C', activebackground='#D5D5D5', font="Montserrat 10", 
cursor="hand2")
cast_power_input.place(x=130, y=85, width=38, height=280)

image_image_11 = PhotoImage(
    file=relative_to_assets("fishingbot/image_11.png"))
image_11 = canvas.create_image(
    58.0,
    228.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("fishingbot/image_12.png"))
image_12 = canvas.create_image(
    83.0,
    75.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("fishingbot/image_13.png"))
image_13 = canvas.create_image(
    400.0,
    32.0,
    image=image_image_13
)

window.resizable(False, False)
window.mainloop()