
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Azoth Lake - v1.6")
window.geometry("800x400")
window.configure(bg = "#1E1D22")

# ----- Window Icon ----- #
p1 = PhotoImage(file=relative_to_assets("favicon.png"))
window.iconphoto(False, p1)

# ----- Canvas Settings ----- #
canvas = Canvas(
    window,
    bg = "#1E1D22",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# ----- Canvas Background ----- #
canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("gatherbot/background.png"))
image_1 = canvas.create_image(
    400.0,
    200.0,
    image=image_image_1
)

# ----- Version + Detection Headings - Text ----- #
canvas.create_text(
    5.0,
    370.0,
    anchor="nw",
    text="Client Version - \nDetection Status -",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Version Status - Text ----- #
canvas.create_text(
    90.0,
    370.0,
    anchor="nw",
    text="Updated",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Detection Status - Text ----- #
canvas.create_text(
    105.0,
    385.0,
    anchor="nw",
    text="Undetected",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Details - Text ----- #
canvas.create_text(
    715.0,
    370.0,
    anchor="ne",
    text="Discord User - \nDiscord Server - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Program Creator Discord - Text ----- #
canvas.create_text(
    795.0,
    370.0,
    anchor="ne",
    text="AzothLake#0261",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Server Link - Text ----- #
canvas.create_text(
    795.0,
    385.0,
    anchor="ne",
    text="vwWJCFkK6a",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Time Remaining Heading - Text ----- #
canvas.create_text(
    323.0,
    380.0,
    anchor="nw",
    text="Time Remaining - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Time Remaining - Text ----- #
canvas.create_text(
    426.0,
    380.0,
    anchor="nw",
    text="365 Days",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Bot Selection/Back Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    botselection_button_image = PhotoImage(file=relative_to_assets("gatherbot/botselection_button-active.png"))
    botselection_button.config(image=botselection_button_image)
    botselection_button.image = botselection_button_image

def on_leave(e):
    botselection_button_image = PhotoImage(file=relative_to_assets("gatherbot/botselection_button.png"))
    botselection_button.config(image=botselection_button_image)
    botselection_button.image = botselection_button_image

# -- Create the button
botselection_button_image = PhotoImage(
    file=relative_to_assets("gatherbot/botselection_button.png"))
botselection_button = Button(
    image=botselection_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Bot Selection button clicked"),
    relief="flat"
)

# -- Place the button
botselection_button.place(
    x=408.0,
    y=295.0,
    width=135.0,
    height=32.0
)

# -- Bind the enter + leave events
botselection_button.bind("<Enter>", on_enter)
botselection_button.bind("<Leave>", on_leave)

# ----- Gather Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    gather_button_image = PhotoImage(file=relative_to_assets("gatherbot/gather_button-active.png"))
    gather_button.config(image=gather_button_image)
    gather_button.image = gather_button_image

def on_leave(e):
    gather_button_image = PhotoImage(file=relative_to_assets("gatherbot/gather_button.png"))
    gather_button.config(image=gather_button_image)
    gather_button.image = gather_button_image

# -- Create the button
gather_button_image = PhotoImage(
    file=relative_to_assets("gatherbot/gather_button.png"))
gather_button = Button(
    image=gather_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Gather button clicked"),
    relief="flat"
)

# -- Place the button
gather_button.place(
    x=256.0,
    y=295.0,
    width=135.0,
    height=32.0
)

# -- Bind the enter + leave events
gather_button.bind("<Enter>", on_enter)
gather_button.bind("<Leave>", on_leave)

# ----- Main Heading - Image ----- #
main_heading_image = PhotoImage(
    file=relative_to_assets("gatherbot/main_heading.png"))
main_heading = canvas.create_image(
    400.0,
    31.0,
    image=main_heading_image
)

# ----- Instructions - Image ----- #
instructions_image = PhotoImage(
    file=relative_to_assets("gatherbot/instructions.png"))
instructions = canvas.create_image(
    400.0,
    168.0,
    image=instructions_image
)
window.resizable(False, False)
window.mainloop()
