
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Azoth Lake - v1.6")
window.geometry("800x400")
window.configure(bg = "#1E1D22")

# ----- Window Icon ----- #
p1 = PhotoImage(file=relative_to_assets("favicon.png"))
window.iconphoto(False, p1)

# ----- Canvas Settings ----- #
canvas = Canvas(
    window,
    bg = "#1E1D22",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# ----- Canvas Background ----- #
canvas.place(x = 0, y = 0)
background_image = PhotoImage(
    file=relative_to_assets("login/background.png"))
background = canvas.create_image(
    401.0,
    200.0,
    image=background_image
)

# ----- Register Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    register_button_image = PhotoImage(file=relative_to_assets("login/register_button-active.png"))
    register_button.config(image=register_button_image)
    register_button.image = register_button_image

def on_leave(e):
    register_button_image = PhotoImage(file=relative_to_assets("login/register_button.png"))
    register_button.config(image=register_button_image)
    register_button.image = register_button_image

# -- Create the button
register_button_image = PhotoImage(
    file=relative_to_assets("login/register_button.png"))
register_button = Button(
    image=register_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Register Button clicked"),
    relief="flat"
)

# -- Place the button
register_button.place(
    x=403.0,
    y=322.0,
    width=105.0,
    height=32.0
)

# -- Bind the enter + leave events
register_button.bind("<Enter>", on_enter)
register_button.bind("<Leave>", on_leave)

# ----- Login Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    login_button_image = PhotoImage(file=relative_to_assets("login/login_button-active.png"))
    login_button.config(image=login_button_image)
    login_button.image = login_button_image

def on_leave(e):
    login_button_image = PhotoImage(file=relative_to_assets("login/login_button.png"))
    login_button.config(image=login_button_image)
    login_button.image = login_button_image    

# -- Create the button
login_button_image = PhotoImage(
    file=relative_to_assets("login/login_button.png"))
login_button = Button(
    image=login_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Login Button clicked"),
    relief="flat"
)

# -- Place the button
login_button.place(
    x=293.0,
    y=322.0,
    width=105.0,
    height=32.0
)

# -- Bind the enter + leave events
login_button.bind("<Enter>", on_enter)
login_button.bind("<Leave>", on_leave)

# ----- Reset Password - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    reset_button_image = PhotoImage(file=relative_to_assets("login/reset_button-active.png"))
    reset_button.config(image=reset_button_image)
    reset_button.image = reset_button_image

def on_leave(e):
    reset_button_image = PhotoImage(file=relative_to_assets("login/reset_button.png"))
    reset_button.config(image=reset_button_image)
    reset_button.image = reset_button_image 

# -- Create the button
reset_button_image = PhotoImage(
    file=relative_to_assets("login/reset_button.png"))
reset_button = Button(
    image=reset_button_image,
    cursor="hand2",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Reset Password Button clicked"),
    relief="flat"
)

# -- Place the button
reset_button.place(
    x=293.0,
    y=361.0,
    width=215.0,
    height=32.0
)

# -- Bind the enter + leave events
reset_button.bind("<Enter>", on_enter)
reset_button.bind("<Leave>", on_leave)

# ----- Version + Detection Headings - Text ----- #
canvas.create_text(
    5.0,
    370.0,
    anchor="nw",
    text="Client Version - \nDetection Status -",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Version Status - Text ----- #
canvas.create_text(
    90.0,
    370.0,
    anchor="nw",
    text="Updated",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Detection Status - Text ----- #
canvas.create_text(
    105.0,
    385.0,
    anchor="nw",
    text="Undetected",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Details - Text ----- #
canvas.create_text(
    715.0,
    370.0,
    anchor="ne",
    text="Discord User - \nDiscord Server - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Program Creator Discord - Text ----- #
canvas.create_text(
    795.0,
    370.0,
    anchor="ne",
    text="AzothLake#0261",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Server Link - Text ----- #
canvas.create_text(
    795.0,
    385.0,
    anchor="ne",
    text="vwWJCFkK6a",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Username Input - TextBox ----- #
username_input_image = PhotoImage(
    file=relative_to_assets("login/username_input.png"))
username_input_bg = canvas.create_image(
    400.5,
    250.0,
    image=username_input_image
)
username_input = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
username_input.insert(0, "Username")
username_input.place(
    x=298.0,
    y=234.0,
    width=205.0,
    height=30.0
)

# ----- Password Input - TextBox ----- #
password_input_image = PhotoImage(
    file=relative_to_assets("login/password_input.png"))
password_input_bg = canvas.create_image(
    400.5,
    294.0,
    image=password_input_image
)
password_input = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1),
    show="*"
)
password_input.insert(0, "password")
password_input.place(
    x=298.0,
    y=278.0,
    width=205.0,
    height=30.0
)

# ----- Heading - Image ----- #
heading_image = PhotoImage(
    file=relative_to_assets("login/heading.png"))
heading = canvas.create_image(
    399.0,
    191.0,
    image=heading_image
)

# ----- Logo - Image ----- #
logo_image = PhotoImage(
    file=relative_to_assets("login/logo.png"))
logo = canvas.create_image(
    400.0,
    94.0,
    image=logo_image 
)
window.resizable(False, False)
window.mainloop()
