
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x400")
window.configure(bg = "#1E1D22")


canvas = Canvas(
    window,
    bg = "#1E1D22",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("reset/image_1.png"))
image_1 = canvas.create_image(
    400.0,
    200.0,
    image=image_image_1
)

back_button_image = PhotoImage(
    file=relative_to_assets("reset/back_button.png"))
back_button = Button(
    image=back_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Back Button clicked"),
    relief="flat"
)
back_button.place(
    x=403.0,
    y=355.0,
    width=105.0,
    height=32.0
)

reset_button_image = PhotoImage(
    file=relative_to_assets("reset/reset_button.png"))
reset_button = Button(
    image=reset_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Reset Button clicked"),
    relief="flat"
)
reset_button.place(
    x=293.0,
    y=355.0,
    width=105.0,
    height=32.0
)

canvas.create_text(
    621.0,
    380.0,
    anchor="nw",
    text="Discord Server - vwWJCFkK6a",
    fill="#D5D5D5",
    font=("MontserratRoman Regular", 11 * -1)
)

canvas.create_text(
    621.0,
    368.0,
    anchor="nw",
    text="Discord User - AzothLake#0261",
    fill="#D5D5D5",
    font=("MontserratRoman Regular", 11 * -1)
)

canvas.create_text(
    5.0,
    380.0,
    anchor="nw",
    text="Detection Status - Undetected",
    fill="#FFFFFF",
    font=("MontserratRoman Regular", 11 * -1)
)

canvas.create_text(
    5.0,
    368.0,
    anchor="nw",
    text="Client Version - Updated",
    fill="#D5D5D5",
    font=("MontserratRoman Regular", 11 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("reset/entry_1.png"))
entry_bg_1 = canvas.create_image(
    398.5,
    135.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0
)
entry_1.place(
    x=296.0,
    y=119.0,
    width=205.0,
    height=30.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("reset/entry_2.png"))
entry_bg_2 = canvas.create_image(
    397.5,
    220.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0
)
entry_2.place(
    x=295.0,
    y=204.0,
    width=205.0,
    height=30.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("reset/entry_3.png"))
entry_bg_3 = canvas.create_image(
    398.5,
    305.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0
)
entry_3.place(
    x=296.0,
    y=289.0,
    width=205.0,
    height=30.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("reset/image_2.png"))
image_2 = canvas.create_image(
    397.0,
    94.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("reset/image_3.png"))
image_3 = canvas.create_image(
    402.0,
    47.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("reset/image_4.png"))
image_4 = canvas.create_image(
    397.0,
    178.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("reset/image_5.png"))
image_5 = canvas.create_image(
    397.0,
    262.0,
    image=image_image_5
)
window.resizable(False, False)
window.mainloop()
