
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Azoth Lake - v1.6")
window.geometry("800x400")
window.configure(bg = "#1E1D22")

# ----- Window Icon ----- #
p1 = PhotoImage(file=relative_to_assets("favicon.png"))
window.iconphoto(False, p1)


canvas = Canvas(
    window,
    bg = "#1E1D22",
    height = 400,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("reset/image_1.png"))
image_1 = canvas.create_image(
    400.0,
    200.0,
    image=image_image_1
)

# ----- Back Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    back_button_image = PhotoImage(file=relative_to_assets("reset/back_button-active.png"))
    back_button.config(image=back_button_image)
    back_button.image = back_button_image

def on_leave(e):
    back_button_image = PhotoImage(file=relative_to_assets("reset/back_button.png"))
    back_button.config(image=back_button_image)
    back_button.image = back_button_image    

# -- Create the button
back_button_image = PhotoImage(
    file=relative_to_assets("reset/back_button.png"))
back_button = Button(
    image=back_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Back Button clicked"),
    relief="flat"
)

# -- Place the button
back_button.place(
    x=403.0,
    y=355.0,
    width=105.0,
    height=32.0
)

# -- Bind the enter + leave events
back_button.bind("<Enter>", on_enter)
back_button.bind("<Leave>", on_leave)


# ----- Reset Button - Button ----- #
# -- Define the mouse enter and leave events
def on_enter(e):
    reset_button_image = PhotoImage(file=relative_to_assets("reset/reset_button-active.png"))
    reset_button.config(image=reset_button_image)
    reset_button.image = reset_button_image

def on_leave(e):
    reset_button_image = PhotoImage(file=relative_to_assets("reset/reset_button.png"))
    reset_button.config(image=reset_button_image)
    reset_button.image = reset_button_image    

# -- Create the button
reset_button_image = PhotoImage(
    file=relative_to_assets("reset/reset_button.png"))
reset_button = Button(
    image=reset_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Reset Button clicked"),
    relief="flat"
)

# -- Place the button
reset_button.place(
    x=293.0,
    y=355.0,
    width=105.0,
    height=32.0
)

# -- Bind the enter + leave events
reset_button.bind("<Enter>", on_enter)
reset_button.bind("<Leave>", on_leave)

# ----- Version + Detection Headings - Text ----- #
canvas.create_text(
    5.0,
    370.0,
    anchor="nw",
    text="Client Version - \nDetection Status -",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Version Status - Text ----- #
canvas.create_text(
    90.0,
    370.0,
    anchor="nw",
    text="Updated",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Detection Status - Text ----- #
canvas.create_text(
    105.0,
    385.0,
    anchor="nw",
    text="Undetected",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Details - Text ----- #
canvas.create_text(
    715.0,
    370.0,
    anchor="ne",
    text="Discord User - \nDiscord Server - ",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Program Creator Discord - Text ----- #
canvas.create_text(
    795.0,
    370.0,
    anchor="ne",
    text="AzothLake#0261",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Discord Server Link - Text ----- #
canvas.create_text(
    795.0,
    385.0,
    anchor="ne",
    text="vwWJCFkK6a",
    fill="#24FF00",
    font=("Montserrat Regular", 11 * -1)
)

# ----- Forgot Password Info - Text ----- #
canvas.create_text(
    230.0,
    331.0,
    anchor="nw",
    text="If you forgot your password, create a ticket in the Discord Server",
    fill="#D5D5D5",
    font=("Montserrat Regular", 11 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("reset/entry_1.png"))
entry_bg_1 = canvas.create_image(
    398.5,
    135.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1)
)
entry_1.place(
    x=296.0,
    y=119.0,
    width=205.0,
    height=30.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("reset/entry_2.png"))
entry_bg_2 = canvas.create_image(
    397.5,
    220.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1),
    show="*"
)
entry_2.place(
    x=295.0,
    y=204.0,
    width=205.0,
    height=30.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("reset/entry_3.png"))
entry_bg_3 = canvas.create_image(
    398.5,
    305.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#28272E",
    highlightthickness=0,
    fg="#d5d5d5",
    insertbackground="#d5d5d5",
    justify='center',
    font=("Montserrat Regular", 14 * -1),
    show="*"
)
entry_3.place(
    x=296.0,
    y=289.0,
    width=205.0,
    height=30.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("reset/image_2.png"))
image_2 = canvas.create_image(
    397.0,
    94.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("reset/image_3.png"))
image_3 = canvas.create_image(
    402.0,
    47.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("reset/image_4.png"))
image_4 = canvas.create_image(
    397.0,
    178.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("reset/image_5.png"))
image_5 = canvas.create_image(
    397.0,
    262.0,
    image=image_image_5
)
window.resizable(False, False)
window.mainloop()
